[package]
name = "bench"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
formato = {path="../formato"}


[dev-dependencies]
criterion= "0.4.0"

[[bench]]
name = "benchmarks"
harness = false